#!/usr/bin/env python

import cgi, cgitb, os

form = cgi.FieldStorage()

temp = form.getvalue('temp')
humi = form.getvalue('humi')
baro = form.getvalue('baro')
phot = form.getvalue('phot')

temp = temp[:32]
humi = humi[:32]
baro = baro[:32]
phot = phot[:32]

f = open('/home/pi/sensordata/data.txt', 'w+')
f.write('%s\n' % (temp))
f.write('%s\n' % (humi))
f.write('%s\n' % (baro))
f.write('%s\n' % (phot))
f.close()

print('Content-type: text/html\n\n')
print('<html>')
print('<body>')
print('data upload complete<br>')
print('temp: %s<br>' % (temp))
print('humi: %s<br>' % (humi))
print('baro: %s<br>' % (baro))
print('phot: %s<br>' % (phot))
print('</body>')
print('</html>')
